fix: api update
XadillaX/dloucflare pull request #1
Opened 2018-07-08 18:38 UTC by mapleincode

2018-07-10 04:16 UTC, XadillaX requested changes

2018-07-10 04:16 UTC, XadillaX commented on lib/dloucflare.js
> +
空格。

2018-07-10 09:05 UTC, mapleincode commented on lib/dloucflare.js
> +
fix.

2018-07-11 03:08 UTC, XadillaX requested changes
如果能把 `sugar` 替换掉更好了，不过目前卡住的就是一个双引号。

2018-07-11 03:08 UTC, XadillaX commented on lib/dloucflare.js
> +var qs = require('querystring');
双引号。

2018-07-11 06:02 UTC, mapleincode commented
fixed.

2018-07-11 06:38 UTC, XadillaX approved these changes

2018-07-11 06:38 UTC, merged